# Generated by Django 4.1.5 on 2023-03-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_item_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="id",
        ),
        migrations.AddField(
            model_name="item",
            name="item_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
