# Generated by Django 4.1.5 on 2023-03-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_tradeoffer_item_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeoffer",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
